//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.27 at 04:50:21 PM ART 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://hallowiner.com/examples/springSoap/soap/models", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.hallowiner.examples.springSoap.soap.models;
